[package]
name = "positron"
version = "0.2.1"
edition = "2026"
repo = "git+https://github.com/vahan-gev/tachyon-positron"

[build]
native-macos = ["native/positron_macos.m"]
link-macos = ["-framework Cocoa", "-framework WebKit"]
native-linux = ["native/positron_linux.c"]
link-linux = ["$(pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.1 2>/dev/null || pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0)"]
native-windows = ["native/positron_win32.c"]
link-windows = ["-lole32", "-loleaut32", "-lgdi32", "-luser32"]
